# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Enable C++ support
language: cpp
python:
  - "3.6"

# Compiler selection
compiler:
  - clang

# Setup anaconda
before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
  - sudo apt-get update -qq

install:
  - conda install -c conda-forge --yes python=$TRAVIS_PYTHON_VERSION pybind11
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install --allow-unauthenticated -qq clang++-4.0
  - export CXX="clang++-4.0" CC="clang-4.0"

# Build steps
script:
  - which python
  - ls /home/travis/miniconda/include/python3.6m/
  - mkdir build
  - cd build
  - cmake .. -DPYBIND11_INCLUDE_DIRS=/home/travis/miniconda/include/python3.6m -DPYTHON_EXECUTABLE=/home/travis/miniconda/bin/python -DPYTHON_INCLUDE_DIR=/home/travis/miniconda/include/ -DPYTHON_LIBRARY=/home/travis/miniconda/lib/libpython3.6m.so
  - make
  - make test

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - lcov

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # filter out system
  - lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
  # debug info
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
