# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Enable C++ support
language: python
python:
  - "3.6"

# Compiler selection
compiler:
  - clang
  - gcc

install:
  - sudo pip install --upgrade pip
  - sudo pip install pybind11

# Build steps
script:
  - which python
  - mkdir build
  - cd build
  - cmake .. -DPYBIND11_INCLUDE_DIRS=/usr/local/anaconda/include/python3.6m
  - make
  - make test

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
    - libboost-all-dev
    - lcov
