# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

#custom install
install:
  - pip install pybind11
  - pip install cppimport

# Build steps
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
    - libboost-all-dev
    - lcov