# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Enable C++ support
language: python
python:
  - "3.4"
  - "3.6"

# Compiler selection
compiler:
  - clang
  - gcc

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pybind11

# Build steps
script:
  - which python
  - ls /home/travis/miniconda/lib/
  - mkdir build
  - cd build
  - cmake .. -DPYBIND11_INCLUDE_DIRS=/home/travis/virtualenv/python3.6.3/include -DPYTHON_EXECUTABLE=/home/travis/virtualenv/python3.6.3/bin/python -DPYTHON_INCLUDE_DIR=/home/travis/virtualenv/python3.6.3/include/python3.6m/ -DPYTHON_LIBRARY=/home/travis/virtualenv/python3.6.3/lib
  - make
  - make test

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
    - libboost-all-dev
    - lcov
